<?php

function get_random_name(): object {
    static $firsts = [
        'Aimee',
        'Albert',
        'Aman',
        'Amber',
        'Andrew',
        'Angela',
        'Anna',
        'Anthony',
        'Ashley',
        'Ben',
        'Benjamin',
        'Bradley',
        'Bree',
        'Brenda',
        'Brian',
        'Briony',
        'Bronte',
        'Bruce',
        'Carol',
        'Catherine',
        'Charles',
        'Chris',
        'David',
        'Deborah',
        'Debra',
        'Diane',
        'Donna',
        'Edward',
        'Elizabeth',
        'Elspeth',
        'Emily',
        'Emma',
        'Eric',
        'Frances',
        'Frank',
        'Fred',
        'Gabriel',
        'Gavin',
        'George',
        'Gregory',
        'Isaac',
        'Jack',
        'Jacob',
        'James',
        'Jane',
        'Jennie',
        'Jeremy',
        'Jesse',
        'John',
        'Jordan',
        'Joseph',
        'Josh',
        'Karen',
        'Kasey',
        'Katherine',
        'Kelly',
        'Kevin',
        'Laura',
        'Lawrence',
        'Lisa',
        'Lori',
        'Louis',
        'Maria',
        'Maya',
        'Melissa',
        'Michael',
        'Michelle',
        'Nicole',
        'Noah',
        'Olivia',
        'Paul',
        'Peter',
        'Raymond',
        'Rebecca',
        'Richard',
        'Rick',
        'Robert',
        'Roy',
        'Ruth',
        'Ryan',
        'Samuel',
        'Sean',
        'Sharna',
        'Sophia',
        'Sophie',
        'Tahlia',
        'Tenita',
        'Thomas',
        'Wayne',
    ];

    static $lasts = [
        'Alexander',
        'Astle',
        'Atkinson',
        'Baker',
        'Bannon',
        'Bell',
        'Bennett',
        'Black',
        'Brown',
        'Butcher',
        'Campbell',
        'Carter',
        'Cavaletti',
        'Chiang',
        'Cole',
        'Coleman',
        'Collins',
        'Cooper',
        'Cox',
        'Davis',
        'Dixon',
        'Eddison',
        'Elliott',
        'Ellis',
        'Elliss',
        'Ellisson',
        'Evans',
        'Fanta',
        'Forbes',
        'Ford',
        'Gee',
        'Gomez',
        'Hammond',
        'Harriss',
        'Hawkins',
        'Hernandez',
        'Herne',
        'Hill',
        'Hyman',
        'Innman',
        'Irons',
        'Johnson',
        'Kelly',
        'Kennedy',
        'King',
        'Lewis',
        'Lions',
        'Lyons',
        'Maker',
        'Matthews',
        'Miller',
        'Moore',
        'Neill',
        'Nicholls',
        'Nicoles',
        'Night',
        'Nixon',
        'Phelps',
        'Phillips',
        'Price',
        'Reed',
        'Roberts',
        'Rose',
        'Rowling',
        'Rule',
        'Simms',
        'Simpson',
        'Sinclair',
        'Singh',
        'Smith',
        'Smyth',
        'Stewart',
        'Street',
        'Stuarts',
        'Taylor',
        'Thomas',
        'Trump',
        'Wang',
        'Ware',
        'Watson',
        'West',
        'Whittington',
        'Williamson',
        'Wilson',
        'Wood',
        'Woods',
        'Wright',
        'Wu',
        'Xu',
        'Young',
        'Zhang',
    ];

    $record = (object) [
        'firstname' =>  $firsts[rand(0, count($firsts) - 1)],
        'lastname' => $lasts[rand(0, count($lasts) - 1)],
    ];
    $record->llastname = strtolower($record->lastname);

    unset($firsts[$record->firstname]);
    unset($lasts[$record->lastname]);

    return $record;
}

$content = '';
for ($i = 1; $i <= 100; $i++) {
    $person = get_random_name();
    $content .= <<<EOF
dn: cn={$person->firstname} {$person->lastname},ou=Users,dc=openstack,dc=org
objectclass: inetOrgPerson
cn: {$person->firstname} {$person->lastname}
sn: {$person->lastname}
givenName: {$person->firstname}
uid: u{$i}
userpassword: test
mail: user{$i}@example.com
ou: Moodle


EOF;
}

file_put_contents(__DIR__ . '/moodle.ldif', $content);
